# Generated by Django 2.2.7 on 2019-11-26 12:15

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_slider_title', models.CharField(max_length=155)),
                ('dest_slider_subtitle', models.CharField(max_length=100)),
                ('dest_slider_image', models.ImageField(default='', upload_to='')),
                ('dest_profile_title', models.CharField(max_length=255)),
                ('dest_profile_image', models.ImageField(default='', upload_to='')),
                ('dest_category', models.CharField(choices=[('religious', 'Religious'), ('waterbody', 'Water Body'), ('adventure', 'Adventurous'), ('nature', 'Nature Seeing')], default='nature', max_length=100)),
                ('dest_location', models.CharField(max_length=100)),
                ('dest_latitude', models.FloatField(max_length=100)),
                ('dest_longitude', models.FloatField(max_length=100)),
                ('dest_content', tinymce.models.HTMLField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
