# Generated by Django 2.2.7 on 2019-11-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191126_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='updated',
        ),
    ]
