# Generated by Django 2.2.7 on 2019-11-26 14:16

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_destination_updated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destination',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='destination',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
