# Generated by Django 2.2.7 on 2019-11-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191126_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
    ]
