# Generated by Django 2.2.7 on 2019-11-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191126_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
    ]
