# Generated by Django 2.2.7 on 2019-11-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191126_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='publish',
        ),
    ]
