# Generated by Django 2.2.7 on 2019-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191126_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_category',
            field=models.CharField(choices=[('religious', 'Religious'), ('waterbody', 'Water Body'), ('adventure', 'Adventurous'), ('nature', 'Nature Seeing')], default='nature', max_length=10),
        ),
    ]
