# Generated by Django 2.2.7 on 2019-11-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191126_2229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destination',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='status',
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_category',
            field=models.CharField(choices=[('religious', 'Religious'), ('waterbody', 'Water Body'), ('adventure', 'Adventurous'), ('nature', 'Nature Seeing')], default='nature', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_slider_title',
            field=models.CharField(max_length=255),
        ),
    ]
