# Generated by Django 2.2.7 on 2019-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191127_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_profile_image',
            field=models.ImageField(default='media/two.jpg', upload_to='media/'),
        ),
    ]
