# Generated by Django 2.2.7 on 2019-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_slider_image',
            field=models.ImageField(upload_to='main/media/'),
        ),
    ]
