# Generated by Django 2.2.7 on 2019-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191127_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_profile_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_slider_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
