# Generated by Django 2.2.7 on 2019-11-28 06:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191127_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', phone_field.models.PhoneField(max_length=55)),
                ('file', models.FileField(upload_to='')),
                ('submited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
