# Generated by Django 2.2.7 on 2019-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sharestory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharestory',
            name='file',
            field=models.FileField(upload_to='stories/'),
        ),
    ]
