# Generated by Django 2.2.7 on 2019-11-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191128_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='submited',
        ),
        migrations.AlterField(
            model_name='sharestory',
            name='file',
            field=models.FileField(upload_to='stories'),
        ),
    ]
