# Generated by Django 2.2.7 on 2019-11-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191128_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='dest_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
